
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8000:80" 
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    environment:
      DB_HOST: mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - mariadb 

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME} 
      MYSQL_USER: ${DB_USER}   
      MYSQL_PASSWORD: ${DB_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
    ports:
      - "3306:3306" 
    volumes:
      - mariadbdata:/var/lib/mysql 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 

volumes:
  mariadbdata:
